version: '1.0'
name: pipeline-20260322
displayName: pipeline-20260322
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - ''
stages:
  - name: build
    displayName: 构建与打包
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: ebu4_site_pack
        displayName: ebu4-site
        nodeVersion: 20.10.0
        commands:
          - bash scripts/package-prod.sh
        artifacts:
          - name: EBU4_SITE_DEPLOY
            path:
              - ./dist
        strategy: {}
